### PR TITLE
Upgrade all dependencies before installing in CI

### LINKED ISSUE #32: Fix DeprecationWarnings in Python 3.7
See https://travis-ci.com/rlworkgroup/akro/jobs/199317054#L472 for an example log.

### PR DESCRIPTION
**Pull request by krzentner**
This might fix #32 

Our requirements are very poorly specified, in hopes that this will make akro easy to install and allow its users to control their dependencies more precisely. This should let us catch when new versions are going to break akro.

### CODE REVIEW

**Comment by ryanjulian** [comment]
Can you explain the motivation here more clearly? Is it because `pip` is having trouble resolving a stable set of deps? 

I ask because users will also be installing via `pip install akro==foo.bar.baz`, so I think the CI should be testing this path, rather than one with totally-frozen deps.

**Comment by krzentner** [comment]
The original rationale behind this change is that we were getting warnings in CI from our dependencies using deprecated APIs, even though we can use newer versions of our dependencies which don't use any deprecated APIs. This is because pip (on Travis or otherwise) doesn't ensure we get the latest version of our dependencies, just *a* version (whatever is allowed and cached). With this change, in Travis we always get the latest allowed version of our dependencies. This makes the CI more predictable, and should surface breakages from new versions of our dependencies more quickly.

**Comment by ryanjulian** [comment]
Oh I understand. I think you can achieve the same goal with `pip install --ignore-installed`, which will run dependency resolution as if there was nothing pre-installed on the system.

**Comment by ryanjulian** [comment]
Anyway, still LGTM

**Pull request merged**
